#!/usr/bin/env ruby

require 'webrick'

root = File.expand_path 'output'
server = WEBrick::HTTPServer.new Port: 5000, DocumentRoot: root

trap 'INT' do
  server.shutdown
end

trap 'TERM' do
  server.shutdown
end

server.start
